from abc import ABC, abstractmethod
class WorldModel(ABC):
    @abstractmethod
    def predict(self,state,action): ...
    @abstractmethod
    def rollout(self,state,actions): ...
    @abstractmethod
    def uncertainty(self,state,action): ...
