capture_method = dxgi
encoder = nvenc
channels = 2
min_threads = 4
fps = 60
width = 1920
height = 1080
bitrate = 15000000
nvenc_preset = p1
nvenc_tune = ull
nvenc_rc = cbr
nvenc_bframes = 0
nvenc_intra_refresh = true
nvenc_gop_size = 120
fec = false
packet_size = 1200
