name: Fortify AST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '45 15 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
      - name: Run Fortify Scan
        uses: fortify/github-action@ef5539bf4bd9c45c0bd971978f635a69eae55297 # v1.6.2
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PAT }}
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_CLIENT_AUTH_TOKEN }}
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          SC_SAST_SENSOR_VERSION: 24.4.0
