name: Fortify AST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '45 15 * * 3'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run Fortify Scan
        uses: fortify/github-action@0540f6aefd95d12a5fbed40f406d825fad64330e # v1.6.2
        with:
          sast-scan: true
          debricked-sca-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PASSWORD: ${{ secrets.FOD_PAT }}
          SSC_URL: ${{ vars.SSC_URL }}
          SSC_TOKEN: ${{ secrets.SSC_TOKEN }}
          SC_SAST_TOKEN: ${{ secrets.SC_CLIENT_AUTH_TOKEN }}
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
          SC_SAST_SENSOR_VERSION: 24.4.0
